stages:
    - test

run_tests:
    stage: test
    image: python:3.9
    only:
        - semestral
        - semestral-tests
    before_script:
        - python3 -m pip install -r requirements.txt
    script:
        - python3 -m pytest -v
