
PLAYERS_KEEP_COLUMNS_RENAME = {
    'player_id': 'player_id',
    '@id': 'id',
    'url': 'url',
    'username': 'username',
    'followers': 'followers',
    'country': 'country_@id',
    'last_online': 'last_online',
    'joined': 'joined',
    'status': 'status',
    'chess_daily_last_rating': 'daily_rating',
    'chess_daily_last_date': 'daily_last_date',
    'chess_daily_last_rd': 'daily_rd',
    'chess_daily_record_win': 'daily_win',
    'chess_daily_record_loss': 'daily_loss',
    'chess_daily_record_draw': 'daily-draw',
    'chess_rapid_last_rating': 'rapid_rating',
    'chess_rapid_last_date': 'rapid_date',
    'chess_rapid_last_rd': 'rapid_rd',
    'chess_rapid_record_win': 'rapid_win',
    'chess_rapid_record_loss': 'rapid_loss',
    'chess_rapid_record_draw': 'rapid_draw',
    'chess_bullet_last_rating': 'bullet_rating',
    'chess_bullet_last_date': 'bullet_date',
    'chess_bullet_last_rd': 'bullet_rd',
    'chess_bullet_record_win': 'bullet_win',
    'chess_bullet_record_loss': 'bullet_loss',
    'chess_bullet_record_draw': 'bullet_draw',
    'chess_blitz_last_rating': 'blitz_rating',
    'chess_blitz_last_date': 'blitz_date',
    'chess_blitz_last_rd': 'blitz_rd',
    'chess_blitz_record_win': 'blitz_win',
    'chess_blitz_record_loss': 'blitz_loss',
    'chess_blitz_record_draw': 'blitz_draw',
    'tactics_highest_rating': 'tactics_highest_rating',
    'puzzle_rush_best_score': 'puzzle_rush_best_score'
}
